#!/usr/bin/env python3
"""
Phase 3 — Learnable fusion (RichardsonNet-style) on 1D periodic heat equation.

This script trains set-based neural operators to fuse TWO coarse solutions produced by the same
nominal 2nd-order solver (CN + 2nd-order FD), sampled on two different uniform grids:

  Grid A: x_i = i/N
  Grid B: x_i = (i+0.5)/N   (staggered)

It loads Phase-1 .npz files (generated by phase1_generate_heat_periodic_AB.py) containing:
  xA [N], xB [N], t_snap [nt]
  alpha [S], c0 [S], a_sin [S,K], b_cos [S,K]
  uA [S,nt,N], uB [S,nt,N]

Then trains one of the following methods:

  - A_only    : predict truth using only set A = {(xA,uA)}
  - B_only    : predict truth using only set B = {(xB,uB)}
  - union     : predict truth using union set {(xA,uA)} ∪ {(xB,uB)} (no Richardson loss)
  - rich_sup  : two-set fusion + supervised Richardson loss (p=2 by default)
  - rich_self : two-set fusion + self-consistency Richardson loss (regularizer)

All models are permutation-invariant set encoders (DeepSets-style):
  zA = mean_i phi([xA_i, uA_i, alpha, t])
  zB = mean_i phi([xB_i, uB_i, alpha, t])
  z  = psi([zA,zB])
  tau(xq) = trunk([xq, alpha, t])
  u_hat(xq) = <z, tau(xq)>

Supervision uses the exact periodic heat solution computed from stored Fourier coefficients.

Outputs:
  - best.pt checkpoint
  - training_curve.png
  - metrics.json
  - snapshots/*.png (optional)

Example:
  python phase3_train_richardsonnet_heat_periodic_AB.py \
    --npz heat_phase1_data/heat_periodic_AB_CN2_FD2_N100_K16_S2000_T0.2.npz \
    --out_dir heat_phase3_runs \
    --method rich_sup \
    --epochs 2000 --batch_size 64 --q_factor 4 --lambda_rich 1.0 --num_rich 32
"""

from __future__ import annotations

import argparse
import os
import json
from dataclasses import dataclass
from typing import Tuple, Dict, Any, Optional, List

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt


# ============================================================
# 1) Exact periodic heat solution in torch (vectorized)
# ============================================================

def eval_u_exact_periodic_torch(
    c0: torch.Tensor,          # [B,1]
    a_sin: torch.Tensor,       # [B,K]
    b_cos: torch.Tensor,       # [B,K]
    alpha: torch.Tensor,       # [B,1]
    x: torch.Tensor,           # [B,Q] or [B,M]
    t: torch.Tensor,           # [B,1]
) -> torch.Tensor:
    """
    u(x,t) = c0 + sum_{k=1..K} exp(-alpha*(2πk)^2 t) * (a_k sin(2πk x) + b_k cos(2πk x))
    Returns: [B,Q]
    """
    # Ensure shapes
    if c0.ndim == 1:
        c0 = c0.view(-1, 1)
    if alpha.ndim == 1:
        alpha = alpha.view(-1, 1)
    if t.ndim == 1:
        t = t.view(-1, 1)
    if x.ndim == 1:
        x = x.view(1, -1).expand(c0.shape[0], -1)

    B = c0.shape[0]
    K = a_sin.shape[1]
    device = c0.device
    dtype = c0.dtype

    # k: [K]
    k = torch.arange(1, K + 1, device=device, dtype=dtype).view(1, K, 1)  # [1,K,1]
    two_pi = torch.tensor(2.0 * np.pi, device=device, dtype=dtype)

    # x: [B,Q] -> [B,1,Q]
    x_ = x.view(B, 1, -1)

    # exp factor: [B,K,1]
    lam = (two_pi * k) ** 2                         # [1,K,1]
    fac = torch.exp(-alpha.view(B, 1, 1) * lam * t.view(B, 1, 1))  # [B,K,1]

    # trig: [B,K,Q]
    arg = two_pi * k * x_
    s = torch.sin(arg)
    c = torch.cos(arg)

    # coeffs: [B,K,1]
    a = a_sin.view(B, K, 1)
    b = b_cos.view(B, K, 1)

    u = c0.view(B, 1) + torch.sum(fac * (a * s + b * c), dim=1)  # [B,Q]
    return u


# ============================================================
# 2) Dataset: loads Phase-1 .npz and creates (sample,time) pairs
# ============================================================

class HeatABDataset(Dataset):
    def __init__(
        self,
        npz_path: str,
        split: str,
        seed: int = 0,
        train_frac: float = 0.8,
        val_frac: float = 0.1,
        dtype: torch.dtype = torch.float32,
    ):
        super().__init__()
        self.npz_path = npz_path
        self.data = np.load(npz_path)

        # Required keys
        for k in ["xA", "xB", "t_snap", "alpha", "c0", "a_sin", "b_cos", "uA", "uB"]:
            if k not in self.data:
                raise KeyError(f"Missing key '{k}' in {npz_path}")

        # Constants / arrays
        self.xA = torch.tensor(self.data["xA"], dtype=dtype)       # [N]
        self.xB = torch.tensor(self.data["xB"], dtype=dtype)       # [N]
        self.t_snap = torch.tensor(self.data["t_snap"], dtype=dtype)  # [nt]

        # Per-sample params + coefficients
        self.alpha = torch.tensor(self.data["alpha"], dtype=dtype).view(-1, 1)  # [S,1]
        self.c0 = torch.tensor(self.data["c0"], dtype=dtype).view(-1, 1)        # [S,1]
        self.a_sin = torch.tensor(self.data["a_sin"], dtype=dtype)              # [S,K]
        self.b_cos = torch.tensor(self.data["b_cos"], dtype=dtype)              # [S,K]

        # Solver outputs (store on CPU)
        self.uA = torch.tensor(self.data["uA"], dtype=dtype)  # [S,nt,N]
        self.uB = torch.tensor(self.data["uB"], dtype=dtype)  # [S,nt,N]

        self.S, self.nt, self.N = self.uA.shape
        assert self.uB.shape == (self.S, self.nt, self.N)

        # Split by sample id (avoid leakage across times)
        rng = np.random.default_rng(seed)
        perm = rng.permutation(self.S)

        n_train = int(train_frac * self.S)
        n_val = int(val_frac * self.S)
        n_test = self.S - n_train - n_val

        if split == "train":
            self.sample_ids = perm[:n_train]
        elif split == "val":
            self.sample_ids = perm[n_train:n_train + n_val]
        elif split == "test":
            self.sample_ids = perm[n_train + n_val:]
        else:
            raise ValueError("split must be one of: train, val, test")

        self.sample_ids = torch.tensor(self.sample_ids, dtype=torch.long)
        # dataset length: (#sample_ids) * nt
        self.length = int(self.sample_ids.numel() * self.nt)

    def __len__(self) -> int:
        return self.length

    def __getitem__(self, idx: int):
        # map idx -> (local_sample_index, time_index)
        local_s = idx // self.nt
        j = idx % self.nt
        sid = int(self.sample_ids[local_s].item())

        uA_j = self.uA[sid, j, :]  # [N]
        uB_j = self.uB[sid, j, :]  # [N]
        alpha = self.alpha[sid, :] # [1]
        t = self.t_snap[j].view(1) # [1]

        c0 = self.c0[sid, :]       # [1]
        a = self.a_sin[sid, :]     # [K]
        b = self.b_cos[sid, :]     # [K]

        return {
            "uA": uA_j,
            "uB": uB_j,
            "alpha": alpha,
            "t": t,
            "c0": c0,
            "a_sin": a,
            "b_cos": b,
        }


def collate_batch(batch: List[Dict[str, torch.Tensor]]) -> Dict[str, torch.Tensor]:
    out: Dict[str, torch.Tensor] = {}
    for k in batch[0].keys():
        out[k] = torch.stack([b[k] for b in batch], dim=0)
    return out


# ============================================================
# 3) Models: DeepSets encoders + DeepONet-style dot-product decoder
# ============================================================

class MLP(nn.Module):
    def __init__(self, in_dim: int, out_dim: int, hidden: Tuple[int, ...] = (128, 128), act=nn.Tanh):
        super().__init__()
        layers: List[nn.Module] = []
        dims = (in_dim,) + hidden + (out_dim,)
        for i in range(len(dims) - 2):
            layers.append(nn.Linear(dims[i], dims[i+1]))
            layers.append(act())
        layers.append(nn.Linear(dims[-2], dims[-1]))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class TwoSetDeepONet(nn.Module):
    """
    Encodes set A and set B separately (DeepSets), fuses latents, then dot-product with trunk features.
    """
    def __init__(
        self,
        latent_dim: int = 128,
        point_hidden: Tuple[int, ...] = (128, 128),
        trunk_hidden: Tuple[int, ...] = (128, 128),
        fuse_hidden: Tuple[int, ...] = (128, 128),
        act=nn.Tanh,
        use_A: bool = True,
        use_B: bool = True,
    ):
        super().__init__()
        self.latent_dim = latent_dim
        self.use_A = use_A
        self.use_B = use_B

        # Point encoder: [x, u, alpha, t] -> latent_dim
        self.point_mlp = MLP(4, latent_dim, hidden=point_hidden, act=act)

        # Fuse: [zA, zB] -> z
        self.fuse_mlp = MLP(2 * latent_dim, latent_dim, hidden=fuse_hidden, act=act)

        # Trunk: [xq, alpha, t] -> latent_dim
        self.trunk_mlp = MLP(3, latent_dim, hidden=trunk_hidden, act=act)

    def encode_set(self, x: torch.Tensor, u: torch.Tensor, alpha: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        """
        x,u: [B,N], alpha,t: [B,1] -> z: [B,latent_dim]
        """
        B, N = x.shape
        alpha_ = alpha.view(B, 1).expand(B, N)
        t_ = t.view(B, 1).expand(B, N)
        feats = torch.stack([x, u, alpha_, t_], dim=-1)        # [B,N,4]
        e = self.point_mlp(feats.view(B * N, 4)).view(B, N, self.latent_dim)  # [B,N,latent]
        z = e.mean(dim=1)                                      # [B,latent]
        return z

    def forward(
        self,
        xA: torch.Tensor, uA: torch.Tensor,     # [B,N]
        xB: torch.Tensor, uB: torch.Tensor,     # [B,N]
        xq: torch.Tensor,                        # [B,Q]
        alpha: torch.Tensor, t: torch.Tensor,    # [B,1]
    ) -> torch.Tensor:
        B, Q = xq.shape

        if self.use_A:
            zA = self.encode_set(xA, uA, alpha, t)
        else:
            zA = torch.zeros(B, self.latent_dim, device=xq.device, dtype=xq.dtype)

        if self.use_B:
            zB = self.encode_set(xB, uB, alpha, t)
        else:
            zB = torch.zeros(B, self.latent_dim, device=xq.device, dtype=xq.dtype)

        z = self.fuse_mlp(torch.cat([zA, zB], dim=1))  # [B,latent]

        # Trunk
        alpha_q = alpha.view(B, 1).expand(B, Q)
        t_q = t.view(B, 1).expand(B, Q)
        trunk_in = torch.stack([xq, alpha_q, t_q], dim=-1).view(B * Q, 3)  # [B*Q,3]
        tau = self.trunk_mlp(trunk_in).view(B, Q, self.latent_dim)         # [B,Q,latent]

        # Dot product
        u_hat = torch.sum(tau * z.view(B, 1, self.latent_dim), dim=-1)     # [B,Q]
        return u_hat


class OneSetDeepONet(nn.Module):
    """
    Encodes a single union set (DeepSets), then dot-product with trunk features.
    """
    def __init__(
        self,
        latent_dim: int = 128,
        point_hidden: Tuple[int, ...] = (128, 128),
        trunk_hidden: Tuple[int, ...] = (128, 128),
        act=nn.Tanh,
    ):
        super().__init__()
        self.latent_dim = latent_dim
        self.point_mlp = MLP(4, latent_dim, hidden=point_hidden, act=act)
        self.trunk_mlp = MLP(3, latent_dim, hidden=trunk_hidden, act=act)

    def encode_set(self, x: torch.Tensor, u: torch.Tensor, alpha: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        B, N = x.shape
        alpha_ = alpha.view(B, 1).expand(B, N)
        t_ = t.view(B, 1).expand(B, N)
        feats = torch.stack([x, u, alpha_, t_], dim=-1)                     # [B,N,4]
        e = self.point_mlp(feats.view(B * N, 4)).view(B, N, self.latent_dim)
        return e.mean(dim=1)                                                # [B,latent]

    def forward(self, xU: torch.Tensor, uU: torch.Tensor, xq: torch.Tensor, alpha: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        B, Q = xq.shape
        z = self.encode_set(xU, uU, alpha, t)                               # [B,latent]

        alpha_q = alpha.view(B, 1).expand(B, Q)
        t_q = t.view(B, 1).expand(B, Q)
        trunk_in = torch.stack([xq, alpha_q, t_q], dim=-1).view(B * Q, 3)
        tau = self.trunk_mlp(trunk_in).view(B, Q, self.latent_dim)

        return torch.sum(tau * z.view(B, 1, self.latent_dim), dim=-1)       # [B,Q]


# ============================================================
# 4) Training + evaluation utilities
# ============================================================

@torch.no_grad()
def compute_batch_metrics(u_hat: torch.Tensor, u_true: torch.Tensor) -> Dict[str, float]:
    """
    u_hat,u_true: [B,Q]
    """
    err = u_hat - u_true
    rmse = torch.sqrt(torch.mean(err**2, dim=1))        # [B]
    linf = torch.max(torch.abs(err), dim=1).values      # [B]
    return {
        "rmse_mean": float(rmse.mean().item()),
        "rmse_median": float(rmse.median().item()),
        "linf_mean": float(linf.mean().item()),
        "linf_median": float(linf.median().item()),
    }


def make_xref(Q: int, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
    # uniform [0,1) grid
    x = torch.linspace(0.0, 1.0, Q + 1, device=device, dtype=dtype)[:-1]
    return x


def train_one_method(
    method: str,
    train_loader: DataLoader,
    val_loader: DataLoader,
    xA: torch.Tensor, xB: torch.Tensor,   # [N] constants on CPU
    x_ref: torch.Tensor,                  # [Q] on device
    K: int,
    out_dir: str,
    epochs: int = 2000,
    lr: float = 3e-4,
    weight_decay: float = 1e-4,
    latent_dim: int = 128,
    lambda_rich: float = 1.0,
    p: int = 2,
    num_rich: int = 32,
    rich_mode: str = "supervised",  # supervised | self
    use_amp: bool = True,
    device: str = "cuda",
    seed: int = 0,
) -> Dict[str, Any]:

    torch.manual_seed(seed)
    np.random.seed(seed)

    dev = torch.device(device)
    dtype = x_ref.dtype

    # Build model
    if method == "union":
        model = OneSetDeepONet(latent_dim=latent_dim)
    elif method == "A_only":
        model = TwoSetDeepONet(latent_dim=latent_dim, use_A=True, use_B=False)
    elif method == "B_only":
        model = TwoSetDeepONet(latent_dim=latent_dim, use_A=False, use_B=True)
    elif method in ["rich_sup", "rich_self"]:
        model = TwoSetDeepONet(latent_dim=latent_dim, use_A=True, use_B=True)
    else:
        raise ValueError(f"Unknown method: {method}")

    model.to(dev)

    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    sched = torch.optim.lr_scheduler.ReduceLROnPlateau(opt, mode="min", factor=0.5, patience=50, threshold=1e-5)
    scaler = torch.amp.GradScaler(enabled=(use_amp and dev.type == "cuda"))
    mse = nn.MSELoss()

    # constants to device
    xA_dev = xA.to(dev)
    xB_dev = xB.to(dev)

    history = {"train": [], "val": []}
    best_val = float("inf")
    best_path = os.path.join(out_dir, f"{method}_best.pt")

    # Pre-sample k indices tensor for exact eval in torch (handled inside exact eval)
    # Training loop
    for epoch in range(1, epochs + 1):
        model.train()
        train_loss = 0.0
        n_train = 0

        for batch in train_loader:
            uA = batch["uA"].to(dev)                # [B,N]
            uB = batch["uB"].to(dev)                # [B,N]
            alpha = batch["alpha"].to(dev)          # [B,1]
            t = batch["t"].to(dev).view(-1, 1)      # [B,1]
            c0 = batch["c0"].to(dev)                # [B,1]
            a_sin = batch["a_sin"].to(dev)          # [B,K]
            b_cos = batch["b_cos"].to(dev)          # [B,K]
            Bsz = uA.shape[0]

            # Query grid batch
            xq = x_ref.view(1, -1).expand(Bsz, -1)  # [B,Q]

            with torch.autocast(device_type=dev.type, enabled=(use_amp and dev.type == "cuda")):
                # Predict
                if method == "union":
                    # Union set
                    xU = torch.cat([xA_dev.view(1, -1).expand(Bsz, -1),
                                    xB_dev.view(1, -1).expand(Bsz, -1)], dim=1)  # [B,2N]
                    uU = torch.cat([uA, uB], dim=1)
                    u_hat = model(xU, uU, xq, alpha, t)  # [B,Q]
                else:
                    u_hat = model(xA_dev.view(1, -1).expand(Bsz, -1), uA,
                                  xB_dev.view(1, -1).expand(Bsz, -1), uB,
                                  xq, alpha, t)          # [B,Q]

                # Truth
                u_true = eval_u_exact_periodic_torch(c0, a_sin, b_cos, alpha, xq, t)  # [B,Q]

                loss = mse(u_hat, u_true)

                # Richardson regularizer (only for rich_* methods)
                if method in ["rich_sup", "rich_self"]:
                    # sample midpoint indices on B grid
                    # idx: [B,num_rich]
                    idx = torch.randint(low=0, high=xA_dev.numel(), size=(Bsz, num_rich), device=dev)
                    # gather coordinates
                    x_mid = xB_dev[idx]  # [B,M]
                    x_left = xA_dev[idx] # [B,M]
                    x_right = xA_dev[(idx + 1) % xA_dev.numel()]  # [B,M]

                    # predict at those points
                    x_trip = torch.cat([x_left, x_right, x_mid], dim=1)  # [B,3M]
                    u_trip = model(xA_dev.view(1, -1).expand(Bsz, -1), uA,
                                   xB_dev.view(1, -1).expand(Bsz, -1), uB,
                                   x_trip, alpha, t)  # [B,3M]
                    u_left = u_trip[:, :num_rich]
                    u_right = u_trip[:, num_rich:2*num_rich]
                    u_mid = u_trip[:, 2*num_rich:]

                    u_coarse = 0.5 * (u_left + u_right)
                    u_fine = u_mid
                    r = 2.0
                    u_rich = (r**p * u_fine - u_coarse) / (r**p - 1.0)

                    if method == "rich_self" or rich_mode == "self":
                        loss_rich = mse(u_rich, u_fine)
                    else:
                        u_mid_true = eval_u_exact_periodic_torch(c0, a_sin, b_cos, alpha, x_mid, t)  # [B,M]
                        loss_rich = mse(u_rich, u_mid_true)

                    loss = loss + lambda_rich * loss_rich

            opt.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()

            train_loss += float(loss.item()) * Bsz
            n_train += Bsz

        train_loss /= max(1, n_train)

        # Validation
        model.eval()
        val_loss = 0.0
        n_val = 0
        with torch.no_grad():
            for batch in val_loader:
                uA = batch["uA"].to(dev)
                uB = batch["uB"].to(dev)
                alpha = batch["alpha"].to(dev)
                t = batch["t"].to(dev).view(-1, 1)
                c0 = batch["c0"].to(dev)
                a_sin = batch["a_sin"].to(dev)
                b_cos = batch["b_cos"].to(dev)
                Bsz = uA.shape[0]
                xq = x_ref.view(1, -1).expand(Bsz, -1)

                with torch.autocast(device_type=dev.type, enabled=(use_amp and dev.type == "cuda")):
                    if method == "union":
                        xU = torch.cat([xA_dev.view(1, -1).expand(Bsz, -1),
                                        xB_dev.view(1, -1).expand(Bsz, -1)], dim=1)
                        uU = torch.cat([uA, uB], dim=1)
                        u_hat = model(xU, uU, xq, alpha, t)
                    else:
                        u_hat = model(xA_dev.view(1, -1).expand(Bsz, -1), uA,
                                      xB_dev.view(1, -1).expand(Bsz, -1), uB,
                                      xq, alpha, t)

                    u_true = eval_u_exact_periodic_torch(c0, a_sin, b_cos, alpha, xq, t)
                    loss = mse(u_hat, u_true)

                val_loss += float(loss.item()) * Bsz
                n_val += Bsz

        val_loss /= max(1, n_val)
        sched.step(val_loss)

        history["train"].append(train_loss)
        history["val"].append(val_loss)

        if (epoch == 1) or (epoch % 50 == 0):
            lr_now = opt.param_groups[0]["lr"]
            print(f"[{method}] epoch {epoch:05d}/{epochs}  train={train_loss:.4e}  val={val_loss:.4e}  lr={lr_now:.2e}")

        if val_loss < best_val:
            best_val = val_loss
            torch.save({
                "method": method,
                "model_state": model.state_dict(),
                "latent_dim": latent_dim,
                "history": history,
                "best_val": best_val,
            }, best_path)

    # Plot training curve
    os.makedirs(out_dir, exist_ok=True)
    plt.figure()
    plt.plot(history["train"], label="train")
    plt.plot(history["val"], label="val")
    plt.yscale("log")
    plt.xlabel("epoch")
    plt.ylabel("MSE (log)")
    plt.title(f"Training curve: {method}")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, f"{method}_training_curve.png"), dpi=150)
    plt.close()

    return {"best_path": best_path, "history": history, "best_val": best_val}


@torch.no_grad()
def evaluate_method_on_test(
    method: str,
    ckpt_path: str,
    test_loader: DataLoader,
    xA: torch.Tensor, xB: torch.Tensor,
    x_ref: torch.Tensor,
    device: str = "cuda",
    use_amp: bool = True,
    make_snapshots: bool = True,
    snapshot_dir: Optional[str] = None,
    n_snapshots: int = 3,
) -> Dict[str, Any]:

    dev = torch.device(device)

    ckpt = torch.load(ckpt_path, map_location=dev)
    latent_dim = int(ckpt.get("latent_dim", 128))

    if method == "union":
        model = OneSetDeepONet(latent_dim=latent_dim)
    elif method == "A_only":
        model = TwoSetDeepONet(latent_dim=latent_dim, use_A=True, use_B=False)
    elif method == "B_only":
        model = TwoSetDeepONet(latent_dim=latent_dim, use_A=False, use_B=True)
    else:
        # rich_sup or rich_self use same architecture at inference
        model = TwoSetDeepONet(latent_dim=latent_dim, use_A=True, use_B=True)

    model.load_state_dict(ckpt["model_state"])
    model.to(dev).eval()

    xA_dev = xA.to(dev)
    xB_dev = xB.to(dev)
    x_ref = x_ref.to(dev)

    all_rmse = []
    all_linf = []

    for batch in test_loader:
        uA = batch["uA"].to(dev)
        uB = batch["uB"].to(dev)
        alpha = batch["alpha"].to(dev)
        t = batch["t"].to(dev).view(-1, 1)
        c0 = batch["c0"].to(dev)
        a_sin = batch["a_sin"].to(dev)
        b_cos = batch["b_cos"].to(dev)
        Bsz = uA.shape[0]

        xq = x_ref.view(1, -1).expand(Bsz, -1)

        with torch.autocast(device_type=dev.type, enabled=(use_amp and dev.type == "cuda")):
            if method == "union":
                xU = torch.cat([xA_dev.view(1, -1).expand(Bsz, -1),
                                xB_dev.view(1, -1).expand(Bsz, -1)], dim=1)
                uU = torch.cat([uA, uB], dim=1)
                u_hat = model(xU, uU, xq, alpha, t)
            else:
                u_hat = model(xA_dev.view(1, -1).expand(Bsz, -1), uA,
                              xB_dev.view(1, -1).expand(Bsz, -1), uB,
                              xq, alpha, t)

            u_true = eval_u_exact_periodic_torch(c0, a_sin, b_cos, alpha, xq, t)

        err = u_hat - u_true
        rmse = torch.sqrt(torch.mean(err**2, dim=1))  # [B]
        linf = torch.max(torch.abs(err), dim=1).values
        all_rmse.append(rmse.detach().cpu())
        all_linf.append(linf.detach().cpu())

    all_rmse = torch.cat(all_rmse, dim=0).numpy()
    all_linf = torch.cat(all_linf, dim=0).numpy()

    metrics = {
        "rmse_mean": float(all_rmse.mean()),
        "rmse_median": float(np.median(all_rmse)),
        "rmse_std": float(all_rmse.std()),
        "linf_mean": float(all_linf.mean()),
        "linf_median": float(np.median(all_linf)),
        "linf_std": float(all_linf.std()),
        "n_test": int(all_rmse.shape[0]),
    }

    # Snapshot plots (first few batches)
    if make_snapshots:
        if snapshot_dir is None:
            snapshot_dir = os.path.join(os.path.dirname(ckpt_path), "snapshots")
        os.makedirs(snapshot_dir, exist_ok=True)

        snap_done = 0
        for batch in test_loader:
            uA = batch["uA"].to(dev)
            uB = batch["uB"].to(dev)
            alpha = batch["alpha"].to(dev)
            t = batch["t"].to(dev).view(-1, 1)
            c0 = batch["c0"].to(dev)
            a_sin = batch["a_sin"].to(dev)
            b_cos = batch["b_cos"].to(dev)
            Bsz = uA.shape[0]
            xq = x_ref.view(1, -1).expand(Bsz, -1)

            with torch.autocast(device_type=dev.type, enabled=(use_amp and dev.type == "cuda")):
                if method == "union":
                    xU = torch.cat([xA_dev.view(1, -1).expand(Bsz, -1),
                                    xB_dev.view(1, -1).expand(Bsz, -1)], dim=1)
                    uU = torch.cat([uA, uB], dim=1)
                    u_hat = model(xU, uU, xq, alpha, t)
                else:
                    u_hat = model(xA_dev.view(1, -1).expand(Bsz, -1), uA,
                                  xB_dev.view(1, -1).expand(Bsz, -1), uB,
                                  xq, alpha, t)

                u_true = eval_u_exact_periodic_torch(c0, a_sin, b_cos, alpha, xq, t)

            for b in range(Bsz):
                if snap_done >= n_snapshots:
                    break
                x_np = x_ref.detach().cpu().numpy()
                uhat_np = u_hat[b].detach().cpu().numpy()
                utru_np = u_true[b].detach().cpu().numpy()

                plt.figure()
                plt.plot(x_np, utru_np, label="Exact", linewidth=2)
                plt.plot(x_np, uhat_np, "--", label="Model", linewidth=2)
                plt.xlabel("x")
                plt.ylabel("u(x,t)")
                plt.title(f"{method}  sample={snap_done}  t={float(t[b].item()):.3f}  alpha={float(alpha[b].item()):.3f}")
                plt.legend()
                plt.grid(True)
                plt.tight_layout()
                plt.savefig(os.path.join(snapshot_dir, f"{method}_snap_{snap_done:02d}.png"), dpi=150)
                plt.close()
                snap_done += 1

            if snap_done >= n_snapshots:
                break

    return metrics


# ============================================================
# 5) Main
# ============================================================

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--npz", type=str, required=True, help="Path to Phase-1 .npz")
    ap.add_argument("--out_dir", type=str, required=True, help="Output directory for this run")
    ap.add_argument("--method", type=str, default="rich_sup",
                    choices=["A_only", "B_only", "union", "rich_sup", "rich_self"],
                    help="Training method")

    ap.add_argument("--epochs", type=int, default=2000)
    ap.add_argument("--batch_size", type=int, default=64)
    ap.add_argument("--lr", type=float, default=3e-4)
    ap.add_argument("--weight_decay", type=float, default=1e-4)
    ap.add_argument("--latent_dim", type=int, default=128)

    ap.add_argument("--q_factor", type=int, default=4, help="Query grid size Q = q_factor * N")
    ap.add_argument("--lambda_rich", type=float, default=1.0)
    ap.add_argument("--p", type=int, default=2)
    ap.add_argument("--num_rich", type=int, default=32, help="Rich triplets per sample per batch")
    ap.add_argument("--rich_mode", type=str, default="supervised", choices=["supervised", "self"])

    ap.add_argument("--device", type=str, default=("cuda" if torch.cuda.is_available() else "cpu"))
    ap.add_argument("--no_amp", action="store_true")
    ap.add_argument("--seed", type=int, default=0)

    ap.add_argument("--make_snapshots", action="store_true")
    ap.add_argument("--n_snapshots", type=int, default=3)

    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    with open(os.path.join(args.out_dir, "config.json"), "w") as f:
        json.dump(vars(args), f, indent=2)

    # Load datasets
    train_ds = HeatABDataset(args.npz, split="train", seed=args.seed)
    val_ds = HeatABDataset(args.npz, split="val", seed=args.seed)
    test_ds = HeatABDataset(args.npz, split="test", seed=args.seed)

    # DataLoaders
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, num_workers=0, collate_fn=collate_batch)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, num_workers=0, collate_fn=collate_batch)
    test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False, num_workers=0, collate_fn=collate_batch)

    # Constants
    xA = train_ds.xA
    xB = train_ds.xB
    N = int(xA.numel())
    K = int(train_ds.a_sin.shape[1])

    dev = torch.device(args.device)
    x_ref = make_xref(args.q_factor * N, dev, dtype=torch.float32)

    # Train
    result = train_one_method(
        method=args.method,
        train_loader=train_loader,
        val_loader=val_loader,
        xA=xA, xB=xB,
        x_ref=x_ref,
        K=K,
        out_dir=args.out_dir,
        epochs=args.epochs,
        lr=args.lr,
        weight_decay=args.weight_decay,
        latent_dim=args.latent_dim,
        lambda_rich=args.lambda_rich,
        p=args.p,
        num_rich=args.num_rich,
        rich_mode=args.rich_mode,
        use_amp=(not args.no_amp),
        device=args.device,
        seed=args.seed,
    )

    # Evaluate
    metrics = evaluate_method_on_test(
        method=args.method,
        ckpt_path=result["best_path"],
        test_loader=test_loader,
        xA=xA, xB=xB,
        x_ref=x_ref,
        device=args.device,
        use_amp=(not args.no_amp),
        make_snapshots=args.make_snapshots,
        snapshot_dir=os.path.join(args.out_dir, "snapshots"),
        n_snapshots=args.n_snapshots,
    )

    out = {
        "npz": args.npz,
        "method": args.method,
        "N": N,
        "K": K,
        "Q": int(x_ref.numel()),
        "best_val": float(result["best_val"]),
        "test_metrics": metrics,
        "best_ckpt": result["best_path"],
    }
    with open(os.path.join(args.out_dir, "metrics.json"), "w") as f:
        json.dump(out, f, indent=2)

    print("\n=== DONE ===")
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main()
