#!/usr/bin/env python3
"""
Phase 2 — Baselines + convergence plots for the 1D periodic heat equation
(two shifted grids A/B) generated by Phase 1.

This script loads one or more .npz files produced by:
  phase1_generate_heat_periodic_AB.py

and computes baseline reconstructions / fusions and errors vs the *exact PDE solution*
(using saved Fourier coefficients).

Baselines implemented (per snapshot time):
  1) A-only: compare uA on xA against exact on xA
  2) B-only: compare uB on xB against exact on xB
  3) Union (raw): values on xU (2N points) formed by interleaving A and B;
                  compare against exact on xU
  4) Richardson-mid (B only): u_rich at xB computed from A endpoints + B midpoint;
                              compare against exact on xB
  5) Richardson-union (symmetric): compute u_rich on xB (A->B) and u_rich on xA (B->A),
                                   interleave to xU; compare against exact on xU

Outputs:
  - CSV of mean/median/std L2 and Linf errors per N, time, method
  - Convergence plots (error vs h) per time snapshot
  - Snapshot plots for one selected sample (optional)
"""

from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# 1) Exact periodic heat solution utilities (vectorized)
# ============================================================

@dataclass
class FourierIC:
    c0: float
    a_sin: np.ndarray  # [K]
    b_cos: np.ndarray  # [K]


def precompute_trig_basis(K: int, x: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """
    Returns sin_basis, cos_basis of shape [K, M] where
      sin_basis[k-1, m] = sin(2π k x_m)
    """
    x = np.asarray(x, dtype=np.float64).reshape(1, -1)  # [1,M]
    k = np.arange(1, K + 1, dtype=np.float64)[:, None]  # [K,1]
    sinB = np.sin(2.0 * np.pi * k * x)
    cosB = np.cos(2.0 * np.pi * k * x)
    return sinB, cosB


def eval_u_exact_batch(
    c0: np.ndarray,         # [S]
    a_sin: np.ndarray,      # [S,K]
    b_cos: np.ndarray,      # [S,K]
    alpha: np.ndarray,      # [S]
    t: float,
    sinB: np.ndarray,       # [K,M]
    cosB: np.ndarray,       # [K,M]
) -> np.ndarray:
    """
    Vectorized exact solution on a fixed x grid with precomputed trig basis.
    Returns u_exact: [S,M]
    """
    c0 = np.asarray(c0, dtype=np.float64).reshape(-1)          # [S]
    a_sin = np.asarray(a_sin, dtype=np.float64)                # [S,K]
    b_cos = np.asarray(b_cos, dtype=np.float64)                # [S,K]
    alpha = np.asarray(alpha, dtype=np.float64).reshape(-1)    # [S]

    K = a_sin.shape[1]
    k = np.arange(1, K + 1, dtype=np.float64)                  # [K]
    omega = (2.0 * np.pi * k) ** 2                              # [K]
    decay = np.exp(-alpha[:, None] * omega[None, :] * float(t)) # [S,K]

    ws = decay * a_sin  # [S,K]
    wc = decay * b_cos  # [S,K]

    # [S,M] = [S,K] @ [K,M]
    u = c0[:, None] + ws @ sinB + wc @ cosB
    return u


# ============================================================
# 2) Baseline fusions for staggered grids
# ============================================================

def interleave_union(uA: np.ndarray, uB: np.ndarray) -> np.ndarray:
    """
    uA: [..., N], uB: [..., N] -> uU: [..., 2N] where
      uU[..., 0::2] = uA, uU[..., 1::2] = uB
    """
    if uA.shape != uB.shape:
        raise ValueError("uA and uB must have the same shape to interleave")
    *lead, N = uA.shape
    uU = np.empty((*lead, 2 * N), dtype=np.float64)
    uU[..., 0::2] = uA
    uU[..., 1::2] = uB
    return uU


def richardson_A_to_B(uA: np.ndarray, uB: np.ndarray, p: int = 2) -> np.ndarray:
    """
    Compute Richardson-improved values at B points (midpoints) using:
      coarse = 0.5*(uA_i + uA_{i+1})   (periodic wrap)
      fine   = uB_i
      rich   = (r^p * fine - coarse) / (r^p - 1), with r=2
    """
    r = 2.0
    uA = np.asarray(uA, dtype=np.float64)
    uB = np.asarray(uB, dtype=np.float64)
    uA_right = np.roll(uA, shift=-1, axis=-1)   # i+1
    u_coarse = 0.5 * (uA + uA_right)
    u_fine = uB
    u_rich = (r**p * u_fine - u_coarse) / (r**p - 1.0)
    return u_rich


def richardson_B_to_A(uA: np.ndarray, uB: np.ndarray, p: int = 2) -> np.ndarray:
    """
    Symmetric Richardson-improved values at A points using B endpoints:
      coarse = 0.5*(uB_{i-1} + uB_i)   (periodic wrap)
      fine   = uA_i
      rich   = (r^p * fine - coarse) / (r^p - 1), with r=2
    """
    r = 2.0
    uA = np.asarray(uA, dtype=np.float64)
    uB = np.asarray(uB, dtype=np.float64)
    uB_left = np.roll(uB, shift=+1, axis=-1)    # i-1
    u_coarse = 0.5 * (uB_left + uB)
    u_fine = uA
    u_rich = (r**p * u_fine - u_coarse) / (r**p - 1.0)
    return u_rich


# ============================================================
# 3) Error metrics
# ============================================================

def l2_error(u: np.ndarray, u_ref: np.ndarray) -> np.ndarray:
    """Return per-sample L2 error over the last axis: sqrt(mean((u-u_ref)^2))."""
    e = np.asarray(u, dtype=np.float64) - np.asarray(u_ref, dtype=np.float64)
    return np.sqrt(np.mean(e * e, axis=-1))


def linf_error(u: np.ndarray, u_ref: np.ndarray) -> np.ndarray:
    """Return per-sample Linf error over the last axis: max(|u-u_ref|)."""
    e = np.asarray(u, dtype=np.float64) - np.asarray(u_ref, dtype=np.float64)
    return np.max(np.abs(e), axis=-1)


def summarize_err(err: np.ndarray) -> Dict[str, float]:
    err = np.asarray(err, dtype=np.float64).reshape(-1)
    return dict(
        mean=float(np.mean(err)),
        median=float(np.median(err)),
        std=float(np.std(err)),
    )


# ============================================================
# 4) Optional: trigonometric interpolation (for pretty snapshot plots)
# ============================================================

def trig_interp_uniform_periodic(u: np.ndarray, xq: np.ndarray) -> np.ndarray:
    """
    Trigonometric interpolation from a uniform periodic grid x_m=m/M to query points xq in [0,1).
    u: [M] real
    xq: [Q]
    returns: [Q] real
    """
    u = np.asarray(u, dtype=np.float64).reshape(-1)
    M = u.shape[0]
    xq = np.asarray(xq, dtype=np.float64).reshape(-1)

    uhat = np.fft.fft(u) / M  # complex Fourier coeffs
    k = np.fft.fftfreq(M, d=1.0 / M)  # integer frequencies (possibly negative)
    # exp(i 2π k x)
    E = np.exp(1j * 2.0 * np.pi * k[:, None] * xq[None, :])  # [M,Q]
    uq = np.real(uhat[:, None] * E).sum(axis=0)
    return uq


# ============================================================
# 5) IO helpers
# ============================================================

def find_npz_files(in_dir: str, regex: str) -> List[str]:
    pat = re.compile(regex)
    out = []
    for fn in os.listdir(in_dir):
        if fn.endswith(".npz") and pat.search(fn):
            out.append(os.path.join(in_dir, fn))
    return sorted(out)


def parse_N_from_filename(path: str) -> int:
    m = re.search(r"_N(\d+)_", os.path.basename(path))
    if not m:
        raise ValueError(f"Could not parse N from filename: {path}")
    return int(m.group(1))


# ============================================================
# 6) Main computation
# ============================================================

def compute_phase2_metrics_for_file(npz_path: str, p_rich: int = 2) -> Tuple[pd.DataFrame, dict]:
    import pandas as pd  # local import to keep top-level minimal

    data = np.load(npz_path)
    N = int(data["N"])
    K = int(data["K"])
    t_snap = np.asarray(data["t_snap"], dtype=np.float64)
    xA = np.asarray(data["xA"], dtype=np.float64)
    xB = np.asarray(data["xB"], dtype=np.float64)
    alpha = np.asarray(data["alpha"], dtype=np.float64)  # [S]
    c0 = np.asarray(data["c0"], dtype=np.float64)        # [S]
    a_sin = np.asarray(data["a_sin"], dtype=np.float64)  # [S,K]
    b_cos = np.asarray(data["b_cos"], dtype=np.float64)  # [S,K]
    uA = np.asarray(data["uA"], dtype=np.float64)        # [S,nt,N]
    uB = np.asarray(data["uB"], dtype=np.float64)        # [S,nt,N]

    S = uA.shape[0]
    nt = uA.shape[1]
    assert nt == len(t_snap)

    h = 1.0 / N
    # union grid xU: m/(2N), m=0..2N-1
    xU = (np.arange(2 * N, dtype=np.float64) / (2.0 * N))  # [2N]

    # precompute trig basis
    sinA, cosA = precompute_trig_basis(K, xA)
    sinB, cosB = precompute_trig_basis(K, xB)
    sinU, cosU = precompute_trig_basis(K, xU)

    rows = []
    cache = dict(
        N=N, K=K, S=S, t_snap=t_snap, h=h,
        xA=xA, xB=xB, xU=xU,
        uA=uA, uB=uB,
        alpha=alpha, c0=c0, a_sin=a_sin, b_cos=b_cos
    )

    for j, t in enumerate(t_snap):
        uA_j = uA[:, j, :]  # [S,N]
        uB_j = uB[:, j, :]  # [S,N]

        # exact
        uA_ex = eval_u_exact_batch(c0, a_sin, b_cos, alpha, float(t), sinA, cosA)  # [S,N]
        uB_ex = eval_u_exact_batch(c0, a_sin, b_cos, alpha, float(t), sinB, cosB)  # [S,N]
        uU_ex = eval_u_exact_batch(c0, a_sin, b_cos, alpha, float(t), sinU, cosU)  # [S,2N]

        # union raw
        uU_raw = interleave_union(uA_j, uB_j)  # [S,2N]

        # Richardson fusions
        uB_rich = richardson_A_to_B(uA_j, uB_j, p=p_rich)       # [S,N]
        uA_rich = richardson_B_to_A(uA_j, uB_j, p=p_rich)       # [S,N]
        uU_rich = interleave_union(uA_rich, uB_rich)            # [S,2N]

        methods = [
            ("A_only", uA_j, uA_ex),
            ("B_only", uB_j, uB_ex),
            ("Union_raw", uU_raw, uU_ex),
            ("Rich_B_only", uB_rich, uB_ex),
            ("Rich_union", uU_rich, uU_ex),
        ]

        for name, pred, ref in methods:
            e2 = l2_error(pred, ref)     # [S] or [S, ...] collapsed last axis
            einf = linf_error(pred, ref)

            s2 = summarize_err(e2)
            sinf = summarize_err(einf)

            rows.append(dict(
                file=os.path.basename(npz_path),
                N=N,
                h=h,
                t=float(t),
                method=name,
                L2_mean=s2["mean"],
                L2_median=s2["median"],
                L2_std=s2["std"],
                Linf_mean=sinf["mean"],
                Linf_median=sinf["median"],
                Linf_std=sinf["std"],
                points_used=(N if name in ("A_only", "B_only") else 2 * N),
            ))

    df = pd.DataFrame(rows)
    return df, cache


def fit_order(df: "pd.DataFrame", time_value: float, method: str, metric_col: str = "L2_mean") -> Tuple[float, float]:
    """
    Fit log(err) = a + p*log(h) for a fixed time and method.
    Returns (p, exp(a)).
    """
    import pandas as pd
    sub = df[(df["t"] == time_value) & (df["method"] == method)].copy()
    sub = sub.sort_values("h")
    h = sub["h"].to_numpy()
    e = sub[metric_col].to_numpy()
    # avoid zeros
    eps = 1e-300
    x = np.log(h + eps)
    y = np.log(e + eps)
    A = np.vstack([x, np.ones_like(x)]).T
    p_hat, a_hat = np.linalg.lstsq(A, y, rcond=None)[0]
    return float(p_hat), float(np.exp(a_hat))


def make_convergence_plots(df: "pd.DataFrame", out_dir: str, metric_col: str = "L2_mean"):
    os.makedirs(out_dir, exist_ok=True)
    times = sorted(df["t"].unique().tolist())
    methods = df["method"].unique().tolist()

    for t in times:
        plt.figure(figsize=(7, 5))
        for m in methods:
            sub = df[(df["t"] == t) & (df["method"] == m)].sort_values("h")
            plt.loglog(sub["h"], sub[metric_col], marker="o", label=m)

        plt.gca().invert_xaxis()
        plt.xlabel("h = 1/N")
        plt.ylabel(metric_col)
        plt.title(f"Convergence ({metric_col}) at t={t:g}")
        plt.grid(True, which="both", ls="--", alpha=0.5)
        plt.legend()
        fpath = os.path.join(out_dir, f"convergence_{metric_col}_t{t:g}.png")
        plt.tight_layout()
        plt.savefig(fpath, dpi=200)
        plt.close()

    # order summary plot text file
    order_lines = []
    for t in times:
        order_lines.append(f"=== Effective order fits at t={t:g} (metric={metric_col}) ===")
        for m in methods:
            p_hat, c_hat = fit_order(df, t, m, metric_col=metric_col)
            order_lines.append(f"{m:12s}: order ~ {p_hat:6.3f}  (prefactor ~ {c_hat:.3e})")
        order_lines.append("")
    with open(os.path.join(out_dir, f"order_fits_{metric_col}.txt"), "w") as f:
        f.write("\n".join(order_lines))


def make_snapshot_plots(cache_by_N: dict,
                        df_all: "pd.DataFrame",
                        out_dir: str,
                        sample_idx: int = 0,
                        N_for_snapshot: int = None,
                        metric: str = "L2_mean"):
    """
    Pretty plots for one sample at one chosen N:
      exact vs A_only, B_only, Union_raw, Rich_union at each time.
    Uses trig interpolation to a fine x-grid for smooth curves.
    """
    os.makedirs(out_dir, exist_ok=True)

    if N_for_snapshot is None:
        # choose the finest N available
        N_for_snapshot = max(cache_by_N.keys())

    cache = cache_by_N[N_for_snapshot]
    N = cache["N"]
    K = cache["K"]
    t_snap = cache["t_snap"]
    xA, xB, xU = cache["xA"], cache["xB"], cache["xU"]
    uA = cache["uA"][sample_idx]  # [nt,N]
    uB = cache["uB"][sample_idx]  # [nt,N]

    alpha = float(cache["alpha"][sample_idx])
    c0 = float(cache["c0"][sample_idx])
    a_sin = cache["a_sin"][sample_idx]
    b_cos = cache["b_cos"][sample_idx]

    # fine x for plotting
    x_ref = np.linspace(0.0, 1.0, 2000, endpoint=False)

    # precompute trig basis for exact on x_ref
    sinR, cosR = precompute_trig_basis(K, x_ref)
    c0v = np.array([c0])
    av = a_sin[None, :]
    bv = b_cos[None, :]
    alphav = np.array([alpha])

    for j, t in enumerate(t_snap):
        # exact
        u_ex = eval_u_exact_batch(c0v, av, bv, alphav, float(t), sinR, cosR).reshape(-1)

        # methods on their native grids
        uA_j = uA[j]
        uB_j = uB[j]
        uU_raw = interleave_union(uA_j, uB_j)          # [2N]
        uB_rich = richardson_A_to_B(uA_j, uB_j, p=2)   # [N]
        uA_rich = richardson_B_to_A(uA_j, uB_j, p=2)   # [N]
        uU_rich = interleave_union(uA_rich, uB_rich)   # [2N]

        # trig interp to x_ref for smooth curves
        uA_ref = trig_interp_uniform_periodic(uA_j, x_ref)
        uB_ref = trig_interp_uniform_periodic(uB_j, x_ref)  # note: B is uniform too
        uUraw_ref = trig_interp_uniform_periodic(uU_raw, x_ref)
        uUrich_ref = trig_interp_uniform_periodic(uU_rich, x_ref)

        plt.figure(figsize=(8, 4.8))
        plt.plot(x_ref, u_ex, label="Exact", linewidth=2)
        plt.plot(x_ref, uA_ref, "--", label="A_only (interp)", linewidth=1.5)
        plt.plot(x_ref, uB_ref, "--", label="B_only (interp)", linewidth=1.5)
        plt.plot(x_ref, uUraw_ref, ":", label="Union_raw (interp)", linewidth=2)
        plt.plot(x_ref, uUrich_ref, "-.", label="Rich_union (interp)", linewidth=2)
        plt.scatter(xA, uA_j, s=8, alpha=0.5, label="A points")
        plt.scatter(xB, uB_j, s=8, alpha=0.5, label="B points")

        plt.title(f"Snapshot sample={sample_idx}, N={N}, t={t:g}, alpha={alpha:.3g}")
        plt.xlabel("x")
        plt.ylabel("u(x,t)")
        plt.grid(True, alpha=0.4)
        plt.legend(ncol=2, fontsize=9)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, f"snapshot_N{N}_s{sample_idx}_t{t:g}.png"), dpi=200)
        plt.close()


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--in_dir", type=str, default="heat_phase1_data",
                   help="Directory containing Phase-1 .npz files.")
    p.add_argument("--file_regex", type=str, default=r"heat_periodic_AB_CN2_FD2_N\d+_K\d+_S\d+_T.*\.npz",
                   help="Regex to select input .npz files by filename.")
    p.add_argument("--out_dir", type=str, default="heat_phase2_baselines",
                   help="Output directory for metrics + plots.")
    p.add_argument("--p_rich", type=int, default=2, help="Nominal order p for Richardson fusion (default 2).")
    p.add_argument("--metric", type=str, default="L2_mean", choices=["L2_mean", "Linf_mean"],
                   help="Metric column to plot and fit for convergence.")
    p.add_argument("--make_snapshots", action="store_true",
                   help="Also make snapshot plots for one sample at the finest N.")
    p.add_argument("--snapshot_sample_idx", type=int, default=0)
    p.add_argument("--snapshot_N", type=int, default=None)
    return p.parse_args()


def main():
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    files = find_npz_files(args.in_dir, args.file_regex)
    if len(files) == 0:
        raise FileNotFoundError(f"No .npz files found in {args.in_dir} matching regex: {args.file_regex}")

    import pandas as pd

    dfs = []
    cache_by_N = {}
    for fp in files:
        N = parse_N_from_filename(fp)
        print(f"Processing N={N}: {os.path.basename(fp)}")
        dfN, cache = compute_phase2_metrics_for_file(fp, p_rich=args.p_rich)
        dfs.append(dfN)
        cache_by_N[N] = cache

    df_all = pd.concat(dfs, axis=0, ignore_index=True)
    df_all = df_all.sort_values(["t", "method", "h"])

    # Save metrics
    csv_path = os.path.join(args.out_dir, "phase2_metrics.csv")
    df_all.to_csv(csv_path, index=False)
    print("Saved metrics CSV:", csv_path)

    # Plots + order fits
    make_convergence_plots(df_all, out_dir=args.out_dir, metric_col=args.metric)
    print("Saved convergence plots + order fits to:", args.out_dir)

    # Optional snapshots
    if args.make_snapshots:
        snap_dir = os.path.join(args.out_dir, "snapshots")
        make_snapshot_plots(cache_by_N, df_all, out_dir=snap_dir,
                            sample_idx=args.snapshot_sample_idx,
                            N_for_snapshot=args.snapshot_N)
        print("Saved snapshots to:", snap_dir)

    # Print a compact order summary to stdout
    times = sorted(df_all["t"].unique().tolist())
    methods = df_all["method"].unique().tolist()
    print("\n===== Effective order fits (log-log slope) =====")
    for t in times:
        print(f"\n-- t={t:g} --")
        for m in methods:
            p_hat, _ = fit_order(df_all, t, m, metric_col=args.metric)
            print(f"{m:12s}: {p_hat:6.3f}")


if __name__ == "__main__":
    main()
